workon WRN

cd loc-1-scripts
python train_loc_1.py
cd ../loc-2-scripts
python train_loc_2.py
cd ../loc-3-scripts
python train_loc_3.py
cd ../loc-4-scripts
python train_loc_4.py
cd ../loc-5-scripts
python train_loc_5.py
cd ../loc-6-scripts
python train_loc_6.py
cd ../loc-7-scripts
python train_loc_7.py
cd ../loc-8-scripts
python train_loc_8.py
cd ../loc-9-scripts
python train_loc_9.py
